//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsPortal.Models.StudentsDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMISSION_TYPE
    {
        public ADMISSION_TYPE()
        {
            this.JUPEB_PROSPECTIVE_APPLIED_COURSE = new HashSet<JUPEB_PROSPECTIVE_APPLIED_COURSE>();
            this.PROSPECTIVE_APPLIED_COURSE = new HashSet<PROSPECTIVE_APPLIED_COURSE>();
            this.PROSPECTIVE_SECOND_APPLIED_COURSE = new HashSet<PROSPECTIVE_SECOND_APPLIED_COURSE>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int status { get; set; }
    
        public virtual ICollection<JUPEB_PROSPECTIVE_APPLIED_COURSE> JUPEB_PROSPECTIVE_APPLIED_COURSE { get; set; }
        public virtual ICollection<PROSPECTIVE_APPLIED_COURSE> PROSPECTIVE_APPLIED_COURSE { get; set; }
        public virtual ICollection<PROSPECTIVE_SECOND_APPLIED_COURSE> PROSPECTIVE_SECOND_APPLIED_COURSE { get; set; }
    }
}
