//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsPortal.Models.StudentsDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADVERTMEAN
    {
        public ADVERTMEAN()
        {
            this.REFERAL_SYSTEM = new HashSet<REFERAL_SYSTEM>();
        }
    
        public int Id { get; set; }
        public string Means { get; set; }
    
        public virtual ICollection<REFERAL_SYSTEM> REFERAL_SYSTEM { get; set; }
    }
}
