//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsPortal.Models.StudentsDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPOINTMENT
    {
        public long Appointment_Id { get; set; }
        public long Appointment_Entered_By_User { get; set; }
        public long Appointment_Staff_To_Visit { get; set; }
        public string Appointment_Description { get; set; }
        public System.DateTime Date_Entered { get; set; }
        public System.DateTime Appointment_Date { get; set; }
        public string Visitor { get; set; }
        public bool activated { get; set; }
        public string Time_Start { get; set; }
        public string Time_Stop { get; set; }
    
        public virtual USER USER { get; set; }
        public virtual USER USER1 { get; set; }
    }
}
