//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsPortal.Models.StudentsDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUDIT_TRAIL
    {
        public AUDIT_TRAIL()
        {
            this.BLOCKED_IP = new HashSet<BLOCKED_IP>();
        }
    
        public long Audit_Trail_Id { get; set; }
        public string IP_Address { get; set; }
        public Nullable<System.DateTime> Date_Visited { get; set; }
        public string Audit_Action_Description { get; set; }
        public Nullable<long> User_Id { get; set; }
        public string User_Hostname { get; set; }
        public string MVC_Controller_Name { get; set; }
        public string MVC_Action_Name { get; set; }
    
        public virtual USER USER { get; set; }
        public virtual ICollection<BLOCKED_IP> BLOCKED_IP { get; set; }
    }
}
