//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsPortal.Models.StudentsDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class BLOCKED_IP
    {
        public long Id { get; set; }
        public Nullable<long> Audit_Trail_Id { get; set; }
        public Nullable<bool> Blocked { get; set; }
        public Nullable<System.DateTime> Date_Entered { get; set; }
        public string Blocking_Reason { get; set; }
    
        public virtual AUDIT_TRAIL AUDIT_TRAIL { get; set; }
    }
}
