//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsPortal.Models.StudentsDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class CERTIFICATE_OBTAINED
    {
        public CERTIFICATE_OBTAINED()
        {
            this.STAFF_QUALIFICATIONS = new HashSet<STAFF_QUALIFICATIONS>();
        }
    
        public int Cert_Id { get; set; }
        public string Cert_Name { get; set; }
    
        public virtual ICollection<STAFF_QUALIFICATIONS> STAFF_QUALIFICATIONS { get; set; }
    }
}
