//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsPortal.Models.StudentsDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class COUNTRY
    {
        public COUNTRY()
        {
            this.People = new HashSet<PERSON>();
            this.STATEs = new HashSet<STATE>();
        }
    
        public int Country_Id { get; set; }
        public string Country_Name { get; set; }
    
        public virtual ICollection<PERSON> People { get; set; }
        public virtual ICollection<STATE> STATEs { get; set; }
    }
}
