//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsPortal.Models.StudentsDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class COURSE_TIME_TABLE_SCHEDULE
    {
        public long Course_Time_Table_Schedule_Id { get; set; }
        public long Staff_User_Id { get; set; }
        public long Course_Id { get; set; }
        public byte Day_Id { get; set; }
        public string Time_Start { get; set; }
        public string Time_Stop { get; set; }
        public int Session_Semester_Id { get; set; }
        public int Programme_Id { get; set; }
        public bool Activated { get; set; }
    
        public virtual COURSE COURSE { get; set; }
        public virtual DAY DAY { get; set; }
        public virtual PROGRAMME PROGRAMME { get; set; }
        public virtual SESSION_SEMESTER SESSION_SEMESTER { get; set; }
        public virtual USER USER { get; set; }
    }
}
