//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsPortal.Models.StudentsDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class COURSE
    {
        public COURSE()
        {
            this.COURSE_REGISTRATION = new HashSet<COURSE_REGISTRATION>();
            this.COURSE_TIME_TABLE_SCHEDULE = new HashSet<COURSE_TIME_TABLE_SCHEDULE>();
            this.QUIZ_TIME_TABLE_SCHEDULE = new HashSet<QUIZ_TIME_TABLE_SCHEDULE>();
            this.STAFF_COURSE_ALLOCATION = new HashSet<STAFF_COURSE_ALLOCATION>();
        }
    
        public long Course_Id { get; set; }
        public int Course_Type_Id { get; set; }
        public string Course_Code { get; set; }
        public string Course_Name { get; set; }
        public int Level_Id { get; set; }
        public int Department_Id { get; set; }
        public int Course_Unit { get; set; }
        public int Semester_Id { get; set; }
        public Nullable<int> Session_Id { get; set; }
        public Nullable<bool> Activated { get; set; }
    
        public virtual COURSE_TYPE COURSE_TYPE { get; set; }
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        public virtual LEVEL LEVEL { get; set; }
        public virtual ICollection<COURSE_REGISTRATION> COURSE_REGISTRATION { get; set; }
        public virtual SEMESTER SEMESTER { get; set; }
        public virtual SESSION SESSION { get; set; }
        public virtual ICollection<COURSE_TIME_TABLE_SCHEDULE> COURSE_TIME_TABLE_SCHEDULE { get; set; }
        public virtual ICollection<QUIZ_TIME_TABLE_SCHEDULE> QUIZ_TIME_TABLE_SCHEDULE { get; set; }
        public virtual ICollection<STAFF_COURSE_ALLOCATION> STAFF_COURSE_ALLOCATION { get; set; }
    }
}
