//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsPortal.Models.StudentsDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class COURSE_TYPE
    {
        public COURSE_TYPE()
        {
            this.COURSEs = new HashSet<COURSE>();
            this.POSTGRADUATE_COURSE = new HashSet<POSTGRADUATE_COURSE>();
        }
    
        public int Course_Type_Id { get; set; }
        public string Course_Type_Name { get; set; }
    
        public virtual ICollection<COURSE> COURSEs { get; set; }
        public virtual ICollection<POSTGRADUATE_COURSE> POSTGRADUATE_COURSE { get; set; }
    }
}
