//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsPortal.Models.StudentsDetails
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class COURSE_REGISTRATION
    {
        public COURSE_REGISTRATION()
        {
            this.STUDENT_RESULT = new HashSet<STUDENT_RESULT>();
        }
    
        public long Course_Registration_Id { get; set; }
        public long Student_Id { get; set; }
        public int Level_Id { get; set; }
        public int Programme_Id { get; set; }
        public int Department_Id { get; set; }
        public int Session_Id { get; set; }
        public int Semester_Id { get; set; }
        public Nullable<System.DateTime> Date_Registered { get; set; }
        public long Course_Id { get; set; }
        public Nullable<double> Test_Score { get; set; }
        public Nullable<double> Exam_Score { get; set; }
        public Nullable<double> Total_Score { get; set; }
        public Nullable<long> Uploader_Id { get; set; }
        public Nullable<System.DateTime> Date_Uploaded { get; set; }
        public Nullable<int> Student_Grade_Id { get; set; }
        public Nullable<bool> Is_Absent { get; set; }
        public string Absent_Reason { get; set; }
    
        public virtual COURSE COURSE { get; set; }
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        public virtual LEVEL LEVEL { get; set; }
        public virtual PROGRAMME PROGRAMME { get; set; }
        [Display(Name="Select Semseter")]
        public virtual SEMESTER SEMESTER { get; set; }
        [Display(Name="Select Session")]
        public virtual SESSION SESSION { get; set; }
        public virtual STUDENT STUDENT { get; set; }
        public virtual STUDENT_GRADE STUDENT_GRADE { get; set; }
        public virtual USER USER { get; set; }
        public virtual ICollection<STUDENT_RESULT> STUDENT_RESULT { get; set; }
    }
}
