//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsPortal.Models.StudentsDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAY
    {
        public DAY()
        {
            this.COURSE_TIME_TABLE_SCHEDULE = new HashSet<COURSE_TIME_TABLE_SCHEDULE>();
        }
    
        public byte Day_Id { get; set; }
        public string Day_Name { get; set; }
    
        public virtual ICollection<COURSE_TIME_TABLE_SCHEDULE> COURSE_TIME_TABLE_SCHEDULE { get; set; }
    }
}
