//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsPortal.Models.StudentsDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPARTMENT
    {
        public DEPARTMENT()
        {
            this.ADMISSIONS = new HashSet<ADMISSION>();
            this.COURSEs = new HashSet<COURSE>();
            this.COURSE_REGISTRATION = new HashSet<COURSE_REGISTRATION>();
            this.COURSE_UNIT_ALLOCATION = new HashSet<COURSE_UNIT_ALLOCATION>();
            this.ETRANZACT_FEE_SCHEDULE = new HashSet<ETRANZACT_FEE_SCHEDULE>();
            this.FEE_DETAIL = new HashSet<FEE_DETAIL>();
            this.HOSTEL_ALLOCATION_CRITERIA = new HashSet<HOSTEL_ALLOCATION_CRITERIA>();
            this.PROGRAMME_DEPARTMENT = new HashSet<PROGRAMME_DEPARTMENT>();
            this.PROSPECTIVE_APPLIED_COURSE = new HashSet<PROSPECTIVE_APPLIED_COURSE>();
            this.PROSPECTIVE_SECOND_APPLIED_COURSE = new HashSet<PROSPECTIVE_SECOND_APPLIED_COURSE>();
            this.STAFFs = new HashSet<STAFF>();
            this.STUDENT_LEVEL = new HashSet<STUDENT_LEVEL>();
        }
    
        public int Department_Id { get; set; }
        public string Department_Name { get; set; }
        public bool Activated { get; set; }
        public int Faculty_Id { get; set; }
        public string Department_Code { get; set; }
        public Nullable<int> Course_Duration { get; set; }
    
        public virtual ICollection<ADMISSION> ADMISSIONS { get; set; }
        public virtual ICollection<COURSE> COURSEs { get; set; }
        public virtual ICollection<COURSE_REGISTRATION> COURSE_REGISTRATION { get; set; }
        public virtual ICollection<COURSE_UNIT_ALLOCATION> COURSE_UNIT_ALLOCATION { get; set; }
        public virtual FACULTY FACULTY { get; set; }
        public virtual ICollection<ETRANZACT_FEE_SCHEDULE> ETRANZACT_FEE_SCHEDULE { get; set; }
        public virtual ICollection<FEE_DETAIL> FEE_DETAIL { get; set; }
        public virtual ICollection<HOSTEL_ALLOCATION_CRITERIA> HOSTEL_ALLOCATION_CRITERIA { get; set; }
        public virtual ICollection<PROGRAMME_DEPARTMENT> PROGRAMME_DEPARTMENT { get; set; }
        public virtual ICollection<PROSPECTIVE_APPLIED_COURSE> PROSPECTIVE_APPLIED_COURSE { get; set; }
        public virtual ICollection<PROSPECTIVE_SECOND_APPLIED_COURSE> PROSPECTIVE_SECOND_APPLIED_COURSE { get; set; }
        public virtual ICollection<STAFF> STAFFs { get; set; }
        public virtual ICollection<STUDENT_LEVEL> STUDENT_LEVEL { get; set; }
    }
}
