//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsPortal.Models.StudentsDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class ETRANZACT_FEE_SCHEDULE
    {
        public ETRANZACT_FEE_SCHEDULE()
        {
            this.ETRANZACT_PAYMENT = new HashSet<ETRANZACT_PAYMENT>();
            this.OFFLINE_PAYMENT = new HashSet<OFFLINE_PAYMENT>();
        }
    
        public int Etranzact_Fee_Schedule_Id { get; set; }
        public string Etranzact_Fee_Schedule_Name { get; set; }
        public Nullable<int> Programme_Id { get; set; }
        public Nullable<int> Department_Id { get; set; }
        public Nullable<int> Level_Id { get; set; }
        public int Fee_Schedule_Id { get; set; }
    
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        public virtual FEE_SCHEDULE FEE_SCHEDULE { get; set; }
        public virtual LEVEL LEVEL { get; set; }
        public virtual PROGRAMME PROGRAMME { get; set; }
        public virtual ICollection<ETRANZACT_PAYMENT> ETRANZACT_PAYMENT { get; set; }
        public virtual ICollection<OFFLINE_PAYMENT> OFFLINE_PAYMENT { get; set; }
    }
}
