//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsPortal.Models.StudentsDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class ETRANZACT_TERMINAL
    {
        public ETRANZACT_TERMINAL()
        {
            this.ETRANZACT_PAYMENT = new HashSet<ETRANZACT_PAYMENT>();
        }
    
        public int Etranzact_Terminal_Id { get; set; }
        public string Etranzact_Terminal_Code { get; set; }
        public int Fee_Schedule_Id { get; set; }
        public int Session_Id { get; set; }
    
        public virtual ICollection<ETRANZACT_PAYMENT> ETRANZACT_PAYMENT { get; set; }
        public virtual FEE_SCHEDULE FEE_SCHEDULE { get; set; }
        public virtual SESSION SESSION { get; set; }
    }
}
