//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsPortal.Models.StudentsDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENT
    {
        public long Event_Id { get; set; }
        public string Event_Title { get; set; }
        public string Event_Description { get; set; }
        public System.DateTime Event_Start_Date { get; set; }
        public System.DateTime Event_End_Date { get; set; }
        public long Entered_By_User { get; set; }
        public bool activated { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
