//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsPortal.Models.StudentsDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACULTY
    {
        public FACULTY()
        {
            this.DEPARTMENTs = new HashSet<DEPARTMENT>();
            this.STAFFs = new HashSet<STAFF>();
        }
    
        public int Faculty_Id { get; set; }
        public string Faculty_Name { get; set; }
        public bool Activated { get; set; }
    
        public virtual ICollection<DEPARTMENT> DEPARTMENTs { get; set; }
        public virtual ICollection<STAFF> STAFFs { get; set; }
    }
}
