//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsPortal.Models.StudentsDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class FEE
    {
        public FEE()
        {
            this.FEE_DETAIL = new HashSet<FEE_DETAIL>();
        }
    
        public int Fee_Id { get; set; }
        public string Fee_Name { get; set; }
        public string Fee_Description { get; set; }
        public double Fee_Amount { get; set; }
    
        public virtual ICollection<FEE_DETAIL> FEE_DETAIL { get; set; }
    }
}
