//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsPortal.Models.StudentsDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class FEE_DETAIL
    {
        public int Fee_Detail_Id { get; set; }
        public int Fee_Id { get; set; }
        public Nullable<int> Fee_Schedule_Id { get; set; }
        public Nullable<int> Payment_Installment_Id { get; set; }
        public Nullable<int> Programme_Id { get; set; }
        public Nullable<int> Department_Id { get; set; }
        public Nullable<int> Level_Id { get; set; }
        public int Session_Id { get; set; }
        public Nullable<int> Gender_Id { get; set; }
        public Nullable<int> Semester_Id { get; set; }
    
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        public virtual FEE FEE { get; set; }
        public virtual FEE_SCHEDULE FEE_SCHEDULE { get; set; }
        public virtual GENDER GENDER { get; set; }
        public virtual LEVEL LEVEL { get; set; }
        public virtual PAYMENT_INSTALLMENT PAYMENT_INSTALLMENT { get; set; }
        public virtual PROGRAMME PROGRAMME { get; set; }
        public virtual SEMESTER SEMESTER { get; set; }
        public virtual SESSION SESSION { get; set; }
    }
}
