//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsPortal.Models.StudentsDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class GENDER
    {
        public GENDER()
        {
            this.FEE_DETAIL = new HashSet<FEE_DETAIL>();
            this.HOSTEL_ALLOCATION_CRITERIA = new HashSet<HOSTEL_ALLOCATION_CRITERIA>();
            this.HOSTELs = new HashSet<HOSTEL>();
            this.People = new HashSet<PERSON>();
        }
    
        public int Gender_Id { get; set; }
        public string Gender_Name { get; set; }
    
        public virtual ICollection<FEE_DETAIL> FEE_DETAIL { get; set; }
        public virtual ICollection<HOSTEL_ALLOCATION_CRITERIA> HOSTEL_ALLOCATION_CRITERIA { get; set; }
        public virtual ICollection<HOSTEL> HOSTELs { get; set; }
        public virtual ICollection<PERSON> People { get; set; }
    }
}
