//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsPortal.Models.StudentsDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOSTEL_ALLOCATION_CRITERIA
    {
        public long Id { get; set; }
        public int Hostel_Id { get; set; }
        public Nullable<int> Department_Id { get; set; }
        public Nullable<int> Disability { get; set; }
        public Nullable<int> Level_Id { get; set; }
        public Nullable<int> Series_Setting_Id { get; set; }
        public Nullable<long> Room_Id { get; set; }
        public Nullable<long> Room_Corner_Id { get; set; }
        public Nullable<int> Hostel_Gender { get; set; }
    
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        public virtual DISABILITY DISABILITY1 { get; set; }
        public virtual GENDER GENDER { get; set; }
        public virtual HOSTEL HOSTEL { get; set; }
        public virtual LEVEL LEVEL { get; set; }
        public virtual ROOM_CORNER ROOM_CORNER { get; set; }
        public virtual ROOM ROOM { get; set; }
        public virtual SERIES_SETTING SERIES_SETTING { get; set; }
    }
}
