//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsPortal.Models.StudentsDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOSTEL
    {
        public HOSTEL()
        {
            this.HOSTEL_ALLOCATION_CRITERIA = new HashSet<HOSTEL_ALLOCATION_CRITERIA>();
            this.ROOMS = new HashSet<ROOM>();
            this.SERIES_SETTING = new HashSet<SERIES_SETTING>();
        }
    
        public int Hostel_Id { get; set; }
        public string Hostel_Name { get; set; }
        public int Hostel_Gender_Id { get; set; }
        public int Number_of_Series { get; set; }
        public bool Activated { get; set; }
    
        public virtual GENDER GENDER { get; set; }
        public virtual ICollection<HOSTEL_ALLOCATION_CRITERIA> HOSTEL_ALLOCATION_CRITERIA { get; set; }
        public virtual ICollection<ROOM> ROOMS { get; set; }
        public virtual ICollection<SERIES_SETTING> SERIES_SETTING { get; set; }
    }
}
