//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsPortal.Models.StudentsDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class JUPEB_FACULTY
    {
        public JUPEB_FACULTY()
        {
            this.JUPEB_SUBJECT_COMBINATION = new HashSet<JUPEB_SUBJECT_COMBINATION>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int status { get; set; }
    
        public virtual ICollection<JUPEB_SUBJECT_COMBINATION> JUPEB_SUBJECT_COMBINATION { get; set; }
    }
}
