//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsPortal.Models.StudentsDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class JUPEB_SUBJECT_COMBINATION
    {
        public JUPEB_SUBJECT_COMBINATION()
        {
            this.JUPEB_ADMISSIONS = new HashSet<JUPEB_ADMISSIONS>();
            this.JUPEB_PROSPECTIVE_APPLIED_COURSE = new HashSet<JUPEB_PROSPECTIVE_APPLIED_COURSE>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int jupeb_faculty_id { get; set; }
        public int status { get; set; }
        public string short_name { get; set; }
    
        public virtual ICollection<JUPEB_ADMISSIONS> JUPEB_ADMISSIONS { get; set; }
        public virtual JUPEB_FACULTY JUPEB_FACULTY { get; set; }
        public virtual ICollection<JUPEB_PROSPECTIVE_APPLIED_COURSE> JUPEB_PROSPECTIVE_APPLIED_COURSE { get; set; }
    }
}
