//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsPortal.Models.StudentsDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class LEVEL
    {
        public LEVEL()
        {
            this.COURSEs = new HashSet<COURSE>();
            this.COURSE_REGISTRATION = new HashSet<COURSE_REGISTRATION>();
            this.COURSE_UNIT_ALLOCATION = new HashSet<COURSE_UNIT_ALLOCATION>();
            this.ETRANZACT_FEE_SCHEDULE = new HashSet<ETRANZACT_FEE_SCHEDULE>();
            this.FEE_DETAIL = new HashSet<FEE_DETAIL>();
            this.HOSTEL_ALLOCATION_CRITERIA = new HashSet<HOSTEL_ALLOCATION_CRITERIA>();
            this.STUDENT_LEVEL = new HashSet<STUDENT_LEVEL>();
        }
    
        public int Level_Id { get; set; }
        public string Level_Name { get; set; }
    
        public virtual ICollection<COURSE> COURSEs { get; set; }
        public virtual ICollection<COURSE_REGISTRATION> COURSE_REGISTRATION { get; set; }
        public virtual ICollection<COURSE_UNIT_ALLOCATION> COURSE_UNIT_ALLOCATION { get; set; }
        public virtual ICollection<ETRANZACT_FEE_SCHEDULE> ETRANZACT_FEE_SCHEDULE { get; set; }
        public virtual ICollection<FEE_DETAIL> FEE_DETAIL { get; set; }
        public virtual ICollection<HOSTEL_ALLOCATION_CRITERIA> HOSTEL_ALLOCATION_CRITERIA { get; set; }
        public virtual ICollection<STUDENT_LEVEL> STUDENT_LEVEL { get; set; }
    }
}
