//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsPortal.Models.StudentsDetails
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Liberty_Jedi_GodfreyEntities : DbContext
    {
        public Liberty_Jedi_GodfreyEntities()
            : base("name=Liberty_Jedi_GodfreyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADMISSION_TYPE> ADMISSION_TYPE { get; set; }
        public virtual DbSet<ADMISSION> ADMISSIONS { get; set; }
        public virtual DbSet<ADVERTMEAN> ADVERTMEANS { get; set; }
        public virtual DbSet<APPOINTMENT> APPOINTMENTs { get; set; }
        public virtual DbSet<APPOINTMENT_ALLOCATION> APPOINTMENT_ALLOCATION { get; set; }
        public virtual DbSet<AUDIT_ACTION> AUDIT_ACTION { get; set; }
        public virtual DbSet<AUDIT_TRAIL> AUDIT_TRAIL { get; set; }
        public virtual DbSet<BLOCKED_IP> BLOCKED_IP { get; set; }
        public virtual DbSet<BLOOD_GROUP> BLOOD_GROUP { get; set; }
        public virtual DbSet<CERTIFICATE_OBTAINED> CERTIFICATE_OBTAINED { get; set; }
        public virtual DbSet<COUNTRY> COUNTRies { get; set; }
        public virtual DbSet<COURSE> COURSEs { get; set; }
        public virtual DbSet<COURSE_REGISTRATION> COURSE_REGISTRATION { get; set; }
        public virtual DbSet<COURSE_TIME_TABLE_SCHEDULE> COURSE_TIME_TABLE_SCHEDULE { get; set; }
        public virtual DbSet<COURSE_TYPE> COURSE_TYPE { get; set; }
        public virtual DbSet<COURSE_UNIT_ALLOCATION> COURSE_UNIT_ALLOCATION { get; set; }
        public virtual DbSet<DAY> DAYS { get; set; }
        public virtual DbSet<DEPARTMENT> DEPARTMENTs { get; set; }
        public virtual DbSet<DISABILITY> DISABILITies { get; set; }
        public virtual DbSet<ETRANZACT_FEE_SCHEDULE> ETRANZACT_FEE_SCHEDULE { get; set; }
        public virtual DbSet<ETRANZACT_PAYMENT> ETRANZACT_PAYMENT { get; set; }
        public virtual DbSet<ETRANZACT_TERMINAL> ETRANZACT_TERMINAL { get; set; }
        public virtual DbSet<EVENT> EVENTS { get; set; }
        public virtual DbSet<FACULTY> FACULTies { get; set; }
        public virtual DbSet<FEE> FEEs { get; set; }
        public virtual DbSet<FEE_DETAIL> FEE_DETAIL { get; set; }
        public virtual DbSet<FEE_SCHEDULE> FEE_SCHEDULE { get; set; }
        public virtual DbSet<GENDER> GENDERs { get; set; }
        public virtual DbSet<GENOTYPE> GENOTYPEs { get; set; }
        public virtual DbSet<HOSTEL> HOSTELs { get; set; }
        public virtual DbSet<HOSTEL_ALLOCATION_CRITERIA> HOSTEL_ALLOCATION_CRITERIA { get; set; }
        public virtual DbSet<JUPEB_ADMISSIONS> JUPEB_ADMISSIONS { get; set; }
        public virtual DbSet<JUPEB_FACULTY> JUPEB_FACULTY { get; set; }
        public virtual DbSet<JUPEB_PROSPECTIVE_APPLIED_COURSE> JUPEB_PROSPECTIVE_APPLIED_COURSE { get; set; }
        public virtual DbSet<JUPEB_SUBJECT_COMBINATION> JUPEB_SUBJECT_COMBINATION { get; set; }
        public virtual DbSet<LEVEL> LEVELs { get; set; }
        public virtual DbSet<LOCAL_GOVERNMENT> LOCAL_GOVERNMENT { get; set; }
        public virtual DbSet<MAIL> MAILS { get; set; }
        public virtual DbSet<NEWS> NEWS { get; set; }
        public virtual DbSet<NEXT_OF_KIN> NEXT_OF_KIN { get; set; }
        public virtual DbSet<OFFLINE_PAYMENT> OFFLINE_PAYMENT { get; set; }
        public virtual DbSet<PAYBILL_PAYMENT> PAYBILL_PAYMENT { get; set; }
        public virtual DbSet<PAYBILL_PAYMENT_LOG> PAYBILL_PAYMENT_LOG { get; set; }
        public virtual DbSet<PAYMENT> PAYMENTs { get; set; }
        public virtual DbSet<PAYMENT_INSTALLMENT> PAYMENT_INSTALLMENT { get; set; }
        public virtual DbSet<PAYMENT_MEDIUM> PAYMENT_MEDIUM { get; set; }
        public virtual DbSet<PAYSTACK> PAYSTACKs { get; set; }
        public virtual DbSet<PERSON> People { get; set; }
        public virtual DbSet<PERSON_TYPE> PERSON_TYPE { get; set; }
        public virtual DbSet<POSTGRADUATE_ADMISSIONS> POSTGRADUATE_ADMISSIONS { get; set; }
        public virtual DbSet<POSTGRADUATE_APPLIED_COURSE> POSTGRADUATE_APPLIED_COURSE { get; set; }
        public virtual DbSet<POSTGRADUATE_COURSE> POSTGRADUATE_COURSE { get; set; }
        public virtual DbSet<POSTGRADUATE_COURSE_REGISTRATION> POSTGRADUATE_COURSE_REGISTRATION { get; set; }
        public virtual DbSet<POSTGRADUATE_COURSE_UNIT_ALLOCATION> POSTGRADUATE_COURSE_UNIT_ALLOCATION { get; set; }
        public virtual DbSet<POSTGRADUATE_DEPARTMENT> POSTGRADUATE_DEPARTMENT { get; set; }
        public virtual DbSet<POSTGRADUATE_FACULTY> POSTGRADUATE_FACULTY { get; set; }
        public virtual DbSet<POSTGRADUATE_LEVEL> POSTGRADUATE_LEVEL { get; set; }
        public virtual DbSet<POSTGRADUATE_STUDENT> POSTGRADUATE_STUDENT { get; set; }
        public virtual DbSet<POSTGRADUATE_STUDENT_LEVEL> POSTGRADUATE_STUDENT_LEVEL { get; set; }
        public virtual DbSet<PROGRAMME> PROGRAMMEs { get; set; }
        public virtual DbSet<PROGRAMME_DEPARTMENT> PROGRAMME_DEPARTMENT { get; set; }
        public virtual DbSet<PROSPECTIVE_APPLIED_COURSE> PROSPECTIVE_APPLIED_COURSE { get; set; }
        public virtual DbSet<PROSPECTIVE_JAMB_INFORMATION> PROSPECTIVE_JAMB_INFORMATION { get; set; }
        public virtual DbSet<PROSPECTIVE_OLEVEL_EXAM_ATTEMPT> PROSPECTIVE_OLEVEL_EXAM_ATTEMPT { get; set; }
        public virtual DbSet<PROSPECTIVE_OLEVEL_EXAM_TYPE> PROSPECTIVE_OLEVEL_EXAM_TYPE { get; set; }
        public virtual DbSet<PROSPECTIVE_OLEVEL_RESULT> PROSPECTIVE_OLEVEL_RESULT { get; set; }
        public virtual DbSet<PROSPECTIVE_OLEVEL_RESULT_DETAIL> PROSPECTIVE_OLEVEL_RESULT_DETAIL { get; set; }
        public virtual DbSet<PROSPECTIVE_OLEVEL_SUBJECT> PROSPECTIVE_OLEVEL_SUBJECT { get; set; }
        public virtual DbSet<PROSPECTIVE_OLEVEL_SUBJECT_GRADE> PROSPECTIVE_OLEVEL_SUBJECT_GRADE { get; set; }
        public virtual DbSet<PROSPECTIVE_PROGRESS> PROSPECTIVE_PROGRESS { get; set; }
        public virtual DbSet<PROSPECTIVE_SECOND_APPLIED_COURSE> PROSPECTIVE_SECOND_APPLIED_COURSE { get; set; }
        public virtual DbSet<PROSPECTIVE_STUDENT> PROSPECTIVE_STUDENT { get; set; }
        public virtual DbSet<PROSPECTIVE_STUDENT_PREVIOUS_EDUCATION> PROSPECTIVE_STUDENT_PREVIOUS_EDUCATION { get; set; }
        public virtual DbSet<PUBLICATION_TYPE> PUBLICATION_TYPE { get; set; }
        public virtual DbSet<QUIZ_TIME_TABLE_SCHEDULE> QUIZ_TIME_TABLE_SCHEDULE { get; set; }
        public virtual DbSet<REFERAL_SYSTEM> REFERAL_SYSTEM { get; set; }
        public virtual DbSet<REFEREE> REFEREEs { get; set; }
        public virtual DbSet<RELATIONSHIP> RELATIONSHIPs { get; set; }
        public virtual DbSet<RELIGION> RELIGIONs { get; set; }
        public virtual DbSet<REMITA_PAYMENT> REMITA_PAYMENT { get; set; }
        public virtual DbSet<REMITA_PAYMENT_SETTINGS> REMITA_PAYMENT_SETTINGS { get; set; }
        public virtual DbSet<REMITA_SPLIT_DETAILS> REMITA_SPLIT_DETAILS { get; set; }
        public virtual DbSet<RIGHT> RIGHTs { get; set; }
        public virtual DbSet<ROLE> ROLEs { get; set; }
        public virtual DbSet<ROOM_CAPACITY> ROOM_CAPACITY { get; set; }
        public virtual DbSet<ROOM_CORNER> ROOM_CORNER { get; set; }
        public virtual DbSet<ROOM> ROOMS { get; set; }
        public virtual DbSet<SEMESTER> SEMESTERs { get; set; }
        public virtual DbSet<SERIES> SERIES { get; set; }
        public virtual DbSet<SERIES_SETTING> SERIES_SETTING { get; set; }
        public virtual DbSet<SESSION> SESSIONs { get; set; }
        public virtual DbSet<SESSION_SEMESTER> SESSION_SEMESTER { get; set; }
        public virtual DbSet<STAFF> STAFFs { get; set; }
        public virtual DbSet<STAFF_COURSE_ALLOCATION> STAFF_COURSE_ALLOCATION { get; set; }
        public virtual DbSet<STAFF_IMAGES> STAFF_IMAGES { get; set; }
        public virtual DbSet<STAFF_PUBLICATIONS> STAFF_PUBLICATIONS { get; set; }
        public virtual DbSet<STAFF_QUALIFICATIONS> STAFF_QUALIFICATIONS { get; set; }
        public virtual DbSet<STAFF_RATING> STAFF_RATING { get; set; }
        public virtual DbSet<STAFF_TYPE> STAFF_TYPE { get; set; }
        public virtual DbSet<STAFF_WORKING_EXPERIENCE> STAFF_WORKING_EXPERIENCE { get; set; }
        public virtual DbSet<STATE> STATEs { get; set; }
        public virtual DbSet<STATUS> STATUS { get; set; }
        public virtual DbSet<STUDENT> STUDENTs { get; set; }
        public virtual DbSet<STUDENT_CATEGORY> STUDENT_CATEGORY { get; set; }
        public virtual DbSet<STUDENT_GRADE> STUDENT_GRADE { get; set; }
        public virtual DbSet<STUDENT_HOSTEL> STUDENT_HOSTEL { get; set; }
        public virtual DbSet<STUDENT_LEVEL> STUDENT_LEVEL { get; set; }
        public virtual DbSet<STUDENT_RESULT> STUDENT_RESULT { get; set; }
        public virtual DbSet<STUDENT_STATUS> STUDENT_STATUS { get; set; }
        public virtual DbSet<TABLE_LIST> TABLE_LIST { get; set; }
        public virtual DbSet<TITLE> TITLEs { get; set; }
        public virtual DbSet<TRANSCRIPT_CLEARANCE_STATUS> TRANSCRIPT_CLEARANCE_STATUS { get; set; }
        public virtual DbSet<TRANSCRIPT_REQUEST> TRANSCRIPT_REQUEST { get; set; }
        public virtual DbSet<TRANSCRIPT_STATUS> TRANSCRIPT_STATUS { get; set; }
        public virtual DbSet<TRIBE> TRIBEs { get; set; }
        public virtual DbSet<USER> USERs { get; set; }
        public virtual DbSet<USER_RIGHT> USER_RIGHT { get; set; }
        public virtual DbSet<VISITATION_REGISTATION> VISITATION_REGISTATION { get; set; }
        public virtual DbSet<JUPEB_ACADEMIC_REPORT> JUPEB_ACADEMIC_REPORT { get; set; }
        public virtual DbSet<PROSPECTIVE_ACADEMIC_RECORD> PROSPECTIVE_ACADEMIC_RECORD { get; set; }
        public virtual DbSet<STUDENT_HOSTEL_ALLOCATION> STUDENT_HOSTEL_ALLOCATION { get; set; }
        public virtual DbSet<VW_ADMISSION> VW_ADMISSION { get; set; }
        public virtual DbSet<VW_JUPEB_ACADEMIC_REPORT> VW_JUPEB_ACADEMIC_REPORT { get; set; }
        public virtual DbSet<VW_JUPEB_ADMISSION> VW_JUPEB_ADMISSION { get; set; }
        public virtual DbSet<VW_JUPEB_PROSPCTIVE_PAYMENT> VW_JUPEB_PROSPCTIVE_PAYMENT { get; set; }
        public virtual DbSet<VW_JUPEB_PROSPECTIVE> VW_JUPEB_PROSPECTIVE { get; set; }
        public virtual DbSet<VW_JUPEB_PROSPECTIVE_PAYBILL_PAYMENT> VW_JUPEB_PROSPECTIVE_PAYBILL_PAYMENT { get; set; }
        public virtual DbSet<VW_PAYBILL_PROSPECTIVE_PAYMENT> VW_PAYBILL_PROSPECTIVE_PAYMENT { get; set; }
        public virtual DbSet<VW_POSTGRADUATE_ACADEMIC_REPORT> VW_POSTGRADUATE_ACADEMIC_REPORT { get; set; }
        public virtual DbSet<VW_POSTGRADUATE_ADMISSION> VW_POSTGRADUATE_ADMISSION { get; set; }
        public virtual DbSet<VW_POSTGRADUATE_PROSPCTIVE_PAYMENT> VW_POSTGRADUATE_PROSPCTIVE_PAYMENT { get; set; }
        public virtual DbSet<VW_POSTGRADUATE_PROSPECTIVE_OLEVEL> VW_POSTGRADUATE_PROSPECTIVE_OLEVEL { get; set; }
        public virtual DbSet<VW_POSTGRADUATE_PROSPECTIVE_PAYBILL_PAYMENT> VW_POSTGRADUATE_PROSPECTIVE_PAYBILL_PAYMENT { get; set; }
        public virtual DbSet<VW_PROSPECTIVE> VW_PROSPECTIVE { get; set; }
        public virtual DbSet<VW_PROSPECTIVE_ACADEMIC_REPORT> VW_PROSPECTIVE_ACADEMIC_REPORT { get; set; }
        public virtual DbSet<VW_PROSPECTIVE_OLEVEL_RESULT> VW_PROSPECTIVE_OLEVEL_RESULT { get; set; }
        public virtual DbSet<VW_PROSPECTIVE_STUDENT_PAYMENT> VW_PROSPECTIVE_STUDENT_PAYMENT { get; set; }
        public virtual DbSet<VW_STUDENT_DEPARTMENT_HOSTEL_REPORT> VW_STUDENT_DEPARTMENT_HOSTEL_REPORT { get; set; }
        public virtual DbSet<VW_STUDENT_HOSTEL_ALLOCATION> VW_STUDENT_HOSTEL_ALLOCATION { get; set; }
        public virtual DbSet<VW_STUDENT_PAYMENT> VW_STUDENT_PAYMENT { get; set; }
        public virtual DbSet<VW_STUDENT_RESULT> VW_STUDENT_RESULT { get; set; }
        public virtual DbSet<VW_STUDENT_RESULT_TEST> VW_STUDENT_RESULT_TEST { get; set; }
    }
}
