//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsPortal.Models.StudentsDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAIL
    {
        public string Message_Id { get; set; }
        public long Sent_To { get; set; }
        public long Sent_From { get; set; }
        public string Message_Body { get; set; }
        public string Subject { get; set; }
    }
}
