//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsPortal.Models.StudentsDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class NEWS
    {
        public long News_Id { get; set; }
        public string News_Description { get; set; }
        public string News_File_Url { get; set; }
        public int View_By_Person_Type { get; set; }
        public long Entered_By_User { get; set; }
        public System.DateTime Date_Entered { get; set; }
        public bool activated { get; set; }
        public string News_Title { get; set; }
    
        public virtual PERSON_TYPE PERSON_TYPE { get; set; }
        public virtual USER USER { get; set; }
    }
}
