//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsPortal.Models.StudentsDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class NEXT_OF_KIN
    {
        public long Person_Id { get; set; }
        public string Fullname { get; set; }
        public string Mobile_Phone { get; set; }
        public int Relationship_Id { get; set; }
        public string Contact_Address { get; set; }
    
        public virtual PERSON PERSON { get; set; }
        public virtual RELATIONSHIP RELATIONSHIP { get; set; }
    }
}
