//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsPortal.Models.StudentsDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYBILL_PAYMENT_LOG
    {
        public long id { get; set; }
        public string payment_reference { get; set; }
        public string status { get; set; }
        public string amount_in_kobo { get; set; }
        public string amount_in_naira { get; set; }
        public string invoice_amount { get; set; }
        public string account_number { get; set; }
        public string sub_account_code { get; set; }
        public string customer_email { get; set; }
        public string gate_way_reference { get; set; }
        public string gate_way_otp_verification_reference { get; set; }
        public string organization_transaction_reference { get; set; }
        public string pay_bill_transaction_id { get; set; }
        public string card_type { get; set; }
        public string charge_bearer { get; set; }
        public string organization_charge_in_kobo { get; set; }
        public string date_created { get; set; }
        public string is_nigerian_card { get; set; }
        public string ip_address { get; set; }
        public string auth_method { get; set; }
        public string payment_page_type { get; set; }
        public string city { get; set; }
        public string region { get; set; }
        public string country { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
        public System.DateTime transaction_date { get; set; }
        public Nullable<long> payment_id { get; set; }
    
        public virtual PAYMENT PAYMENT { get; set; }
    }
}
