//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsPortal.Models.StudentsDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYMENT_INSTALLMENT
    {
        public PAYMENT_INSTALLMENT()
        {
            this.FEE_DETAIL = new HashSet<FEE_DETAIL>();
            this.PAYMENTs = new HashSet<PAYMENT>();
        }
    
        public int Payment_Installment_Id { get; set; }
        public string Payment_Installment_Name { get; set; }
    
        public virtual ICollection<FEE_DETAIL> FEE_DETAIL { get; set; }
        public virtual ICollection<PAYMENT> PAYMENTs { get; set; }
    }
}
