//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsPortal.Models.StudentsDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYMENT
    {
        public PAYMENT()
        {
            this.PAYBILL_PAYMENT = new HashSet<PAYBILL_PAYMENT>();
            this.PAYBILL_PAYMENT_LOG = new HashSet<PAYBILL_PAYMENT_LOG>();
            this.PAYSTACKs = new HashSet<PAYSTACK>();
            this.TRANSCRIPT_REQUEST = new HashSet<TRANSCRIPT_REQUEST>();
        }
    
        public long Payment_Id { get; set; }
        public long Person_Id { get; set; }
        public int Payment_Installment_Id { get; set; }
        public int Payment_Medium_Id { get; set; }
        public int Fee_Schedule_Id { get; set; }
        public string Invoice_Number { get; set; }
        public System.DateTime Transaction_Date { get; set; }
        public Nullable<int> Session_Id { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Semester_Id { get; set; }
    
        public virtual ETRANZACT_PAYMENT ETRANZACT_PAYMENT { get; set; }
        public virtual FEE_SCHEDULE FEE_SCHEDULE { get; set; }
        public virtual OFFLINE_PAYMENT OFFLINE_PAYMENT { get; set; }
        public virtual ICollection<PAYBILL_PAYMENT> PAYBILL_PAYMENT { get; set; }
        public virtual ICollection<PAYBILL_PAYMENT_LOG> PAYBILL_PAYMENT_LOG { get; set; }
        public virtual PAYMENT_INSTALLMENT PAYMENT_INSTALLMENT { get; set; }
        public virtual PAYMENT_MEDIUM PAYMENT_MEDIUM { get; set; }
        public virtual PERSON PERSON { get; set; }
        public virtual SEMESTER SEMESTER { get; set; }
        public virtual SESSION SESSION { get; set; }
        public virtual ICollection<PAYSTACK> PAYSTACKs { get; set; }
        public virtual REMITA_PAYMENT REMITA_PAYMENT { get; set; }
        public virtual ICollection<TRANSCRIPT_REQUEST> TRANSCRIPT_REQUEST { get; set; }
    }
}
