//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsPortal.Models.StudentsDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYSTACK
    {
        public long PayStack_id { get; set; }
        public decimal Amount { get; set; }
        public string IP { get; set; }
        public string Reference { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public string card { get; set; }
        public string lastFour { get; set; }
        public string bank { get; set; }
        public string email { get; set; }
        public string status { get; set; }
        public string paymentGateway { get; set; }
        public long payment_id { get; set; }
        public string responseData { get; set; }
    
        public virtual PAYMENT PAYMENT { get; set; }
    }
}
