//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsPortal.Models.StudentsDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSTGRADUATE_COURSE_REGISTRATION
    {
        public long id { get; set; }
        public long student_id { get; set; }
        public int level_id { get; set; }
        public int programme_id { get; set; }
        public int department_id { get; set; }
        public int session_id { get; set; }
        public int semester_id { get; set; }
        public System.DateTime date_registered { get; set; }
        public long course_id { get; set; }
        public Nullable<double> test_score { get; set; }
        public Nullable<double> exam_score { get; set; }
        public Nullable<double> total_score { get; set; }
        public Nullable<int> student_grade_id { get; set; }
        public Nullable<bool> is_absent { get; set; }
    
        public virtual POSTGRADUATE_COURSE POSTGRADUATE_COURSE { get; set; }
        public virtual POSTGRADUATE_DEPARTMENT POSTGRADUATE_DEPARTMENT { get; set; }
        public virtual POSTGRADUATE_LEVEL POSTGRADUATE_LEVEL { get; set; }
        public virtual POSTGRADUATE_STUDENT POSTGRADUATE_STUDENT { get; set; }
        public virtual PROGRAMME PROGRAMME { get; set; }
        public virtual SEMESTER SEMESTER { get; set; }
        public virtual STUDENT_GRADE STUDENT_GRADE { get; set; }
    }
}
