//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsPortal.Models.StudentsDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSTGRADUATE_STUDENT
    {
        public POSTGRADUATE_STUDENT()
        {
            this.POSTGRADUATE_COURSE_REGISTRATION = new HashSet<POSTGRADUATE_COURSE_REGISTRATION>();
            this.POSTGRADUATE_STUDENT_LEVEL = new HashSet<POSTGRADUATE_STUDENT_LEVEL>();
        }
    
        public long person_id { get; set; }
        public long postgraduate_admission_id { get; set; }
        public int student_category_id { get; set; }
        public int student_status_id { get; set; }
        public string matric_number { get; set; }
        public string student_status_reason { get; set; }
    
        public virtual PERSON PERSON { get; set; }
        public virtual ICollection<POSTGRADUATE_COURSE_REGISTRATION> POSTGRADUATE_COURSE_REGISTRATION { get; set; }
        public virtual ICollection<POSTGRADUATE_STUDENT_LEVEL> POSTGRADUATE_STUDENT_LEVEL { get; set; }
        public virtual STUDENT_CATEGORY STUDENT_CATEGORY { get; set; }
        public virtual STUDENT_STATUS STUDENT_STATUS { get; set; }
    }
}
