//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsPortal.Models.StudentsDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSTGRADUATE_COURSE
    {
        public POSTGRADUATE_COURSE()
        {
            this.POSTGRADUATE_COURSE_REGISTRATION = new HashSet<POSTGRADUATE_COURSE_REGISTRATION>();
        }
    
        public long course_id { get; set; }
        public int course_type_id { get; set; }
        public string course_code { get; set; }
        public string course_name { get; set; }
        public int level_id { get; set; }
        public int department_id { get; set; }
        public int course_unit { get; set; }
        public int semester_id { get; set; }
        public int session_id { get; set; }
        public bool activated { get; set; }
        public bool is_selected { get; set; }
    
        public virtual COURSE_TYPE COURSE_TYPE { get; set; }
        public virtual POSTGRADUATE_DEPARTMENT POSTGRADUATE_DEPARTMENT { get; set; }
        public virtual POSTGRADUATE_LEVEL POSTGRADUATE_LEVEL { get; set; }
        public virtual ICollection<POSTGRADUATE_COURSE_REGISTRATION> POSTGRADUATE_COURSE_REGISTRATION { get; set; }
        public virtual SEMESTER SEMESTER { get; set; }
        public virtual SESSION SESSION { get; set; }
    }
}
