//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsPortal.Models.StudentsDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSTGRADUATE_STUDENT_LEVEL
    {
        public long postgraduate_student_level_id { get; set; }
        public long postgraduate_student_id { get; set; }
        public int level_id { get; set; }
        public int postgraduate_department_id { get; set; }
        public int session_id { get; set; }
        public int programme_id { get; set; }
    
        public virtual POSTGRADUATE_DEPARTMENT POSTGRADUATE_DEPARTMENT { get; set; }
        public virtual POSTGRADUATE_LEVEL POSTGRADUATE_LEVEL { get; set; }
        public virtual POSTGRADUATE_STUDENT POSTGRADUATE_STUDENT { get; set; }
        public virtual PROGRAMME PROGRAMME { get; set; }
        public virtual SESSION SESSION { get; set; }
    }
}
