//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsPortal.Models.StudentsDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSTGRADUATE_LEVEL
    {
        public POSTGRADUATE_LEVEL()
        {
            this.POSTGRADUATE_COURSE = new HashSet<POSTGRADUATE_COURSE>();
            this.POSTGRADUATE_COURSE_REGISTRATION = new HashSet<POSTGRADUATE_COURSE_REGISTRATION>();
            this.POSTGRADUATE_COURSE_UNIT_ALLOCATION = new HashSet<POSTGRADUATE_COURSE_UNIT_ALLOCATION>();
            this.POSTGRADUATE_STUDENT_LEVEL = new HashSet<POSTGRADUATE_STUDENT_LEVEL>();
        }
    
        public int postgraduate_level_id { get; set; }
        public string postgraduate_level_name { get; set; }
    
        public virtual ICollection<POSTGRADUATE_COURSE> POSTGRADUATE_COURSE { get; set; }
        public virtual ICollection<POSTGRADUATE_COURSE_REGISTRATION> POSTGRADUATE_COURSE_REGISTRATION { get; set; }
        public virtual ICollection<POSTGRADUATE_COURSE_UNIT_ALLOCATION> POSTGRADUATE_COURSE_UNIT_ALLOCATION { get; set; }
        public virtual ICollection<POSTGRADUATE_STUDENT_LEVEL> POSTGRADUATE_STUDENT_LEVEL { get; set; }
    }
}
