//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsPortal.Models.StudentsDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSTGRADUATE_COURSE_UNIT_ALLOCATION
    {
        public int id { get; set; }
        public int department_id { get; set; }
        public int level_id { get; set; }
        public int semester_id { get; set; }
        public byte maximum_unit { get; set; }
        public byte minimum_unit { get; set; }
        public int session_id { get; set; }
        public int compulsary_course_unit { get; set; }
        public int optional_course_unit { get; set; }
    
        public virtual POSTGRADUATE_DEPARTMENT POSTGRADUATE_DEPARTMENT { get; set; }
        public virtual POSTGRADUATE_LEVEL POSTGRADUATE_LEVEL { get; set; }
        public virtual SEMESTER SEMESTER { get; set; }
        public virtual SESSION SESSION { get; set; }
    }
}
