//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsPortal.Models.StudentsDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROSPECTIVE_STUDENT
    {
        public PROSPECTIVE_STUDENT()
        {
            this.ADMISSIONS = new HashSet<ADMISSION>();
            this.JUPEB_ADMISSIONS = new HashSet<JUPEB_ADMISSIONS>();
            this.POSTGRADUATE_ADMISSIONS = new HashSet<POSTGRADUATE_ADMISSIONS>();
            this.REFEREEs = new HashSet<REFEREE>();
        }
    
        public long Person_Id { get; set; }
        public int Progress_Id { get; set; }
        public string Hobbies { get; set; }
        public string Appication_Number { get; set; }
        public Nullable<bool> Admitted { get; set; }
        public Nullable<int> Status_Id { get; set; }
        public string RejectionReason { get; set; }
    
        public virtual ICollection<ADMISSION> ADMISSIONS { get; set; }
        public virtual ICollection<JUPEB_ADMISSIONS> JUPEB_ADMISSIONS { get; set; }
        public virtual PERSON PERSON { get; set; }
        public virtual ICollection<POSTGRADUATE_ADMISSIONS> POSTGRADUATE_ADMISSIONS { get; set; }
        public virtual PROSPECTIVE_PROGRESS PROSPECTIVE_PROGRESS { get; set; }
        public virtual STATUS STATUS { get; set; }
        public virtual ICollection<REFEREE> REFEREEs { get; set; }
    }
}
