//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsPortal.Models.StudentsDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROSPECTIVE_PROGRESS
    {
        public PROSPECTIVE_PROGRESS()
        {
            this.PROSPECTIVE_STUDENT = new HashSet<PROSPECTIVE_STUDENT>();
        }
    
        public int Progress_Id { get; set; }
        public string Progress_Name { get; set; }
    
        public virtual ICollection<PROSPECTIVE_STUDENT> PROSPECTIVE_STUDENT { get; set; }
    }
}
