//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsPortal.Models.StudentsDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROSPECTIVE_STUDENT_PREVIOUS_EDUCATION
    {
        public long id { get; set; }
        public long person_id { get; set; }
        public string institution { get; set; }
        public string certificate_obtained { get; set; }
        public string course_of_study { get; set; }
        public string class_of_certificate { get; set; }
        public Nullable<System.DateTime> date_of_graduation { get; set; }
        public string cgpa { get; set; }
    
        public virtual PERSON PERSON { get; set; }
    }
}
