//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsPortal.Models.StudentsDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROSPECTIVE_ACADEMIC_RECORD
    {
        public string Last_Name { get; set; }
        public string First_Name { get; set; }
        public string Other_Name { get; set; }
        public string Jamb_Registration_Number { get; set; }
        public Nullable<int> Exam_Year { get; set; }
        public Nullable<double> Jamb_Score { get; set; }
        public string OLevel_Subject_Name { get; set; }
        public Nullable<int> Olevel_Exam_Year { get; set; }
        public string Olevel_Exam_Number { get; set; }
        public string OLevel_Subject_Grade_Name { get; set; }
        public string OLevel_Exam_Name { get; set; }
        public string Appication_Number { get; set; }
        public string Session_Name { get; set; }
        public string Programme_Name { get; set; }
        public string OLevel_Exam_Attempt_Name { get; set; }
        public int OLevel_Exam_Attempt_Id { get; set; }
        public int Session_Id { get; set; }
        public int Department_Id { get; set; }
        public string Faculty_Name { get; set; }
        public int Faculty_Id { get; set; }
    }
}
