//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsPortal.Models.StudentsDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROSPECTIVE_OLEVEL_EXAM_ATTEMPT
    {
        public PROSPECTIVE_OLEVEL_EXAM_ATTEMPT()
        {
            this.PROSPECTIVE_OLEVEL_RESULT = new HashSet<PROSPECTIVE_OLEVEL_RESULT>();
        }
    
        public int OLevel_Exam_Attempt_Id { get; set; }
        public string OLevel_Exam_Attempt_Name { get; set; }
    
        public virtual ICollection<PROSPECTIVE_OLEVEL_RESULT> PROSPECTIVE_OLEVEL_RESULT { get; set; }
    }
}
