//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsPortal.Models.StudentsDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUBLICATION_TYPE
    {
        public PUBLICATION_TYPE()
        {
            this.STAFF_PUBLICATIONS = new HashSet<STAFF_PUBLICATIONS>();
        }
    
        public int Publication_Type_Id { get; set; }
        public string Publication_Type_Name { get; set; }
    
        public virtual ICollection<STAFF_PUBLICATIONS> STAFF_PUBLICATIONS { get; set; }
    }
}
