//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsPortal.Models.StudentsDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class REFEREE
    {
        public long Referee_Id { get; set; }
        public long Person_Id { get; set; }
        public string Recommendation_Later { get; set; }
        public long Prospective_Student_Id { get; set; }
        public bool Has_Sent_Email { get; set; }
    
        public virtual PERSON PERSON { get; set; }
        public virtual PROSPECTIVE_STUDENT PROSPECTIVE_STUDENT { get; set; }
    }
}
