//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsPortal.Models.StudentsDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class REFERAL_SYSTEM
    {
        public long Id { get; set; }
        public long Student_Id { get; set; }
        public string referer_name { get; set; }
        public int Advert_id { get; set; }
    
        public virtual ADVERTMEAN ADVERTMEAN { get; set; }
        public virtual PERSON PERSON { get; set; }
    }
}
