//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsPortal.Models.StudentsDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class RELATIONSHIP
    {
        public RELATIONSHIP()
        {
            this.NEXT_OF_KIN = new HashSet<NEXT_OF_KIN>();
        }
    
        public int Relationship_Id { get; set; }
        public string Relationship_Name { get; set; }
        public bool Activated { get; set; }
    
        public virtual ICollection<NEXT_OF_KIN> NEXT_OF_KIN { get; set; }
    }
}
