//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsPortal.Models.StudentsDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class RELIGION
    {
        public RELIGION()
        {
            this.People = new HashSet<PERSON>();
        }
    
        public int Religion_Id { get; set; }
        public string Religion_Name { get; set; }
        public bool Activated { get; set; }
    
        public virtual ICollection<PERSON> People { get; set; }
    }
}
