//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsPortal.Models.StudentsDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class REMITA_PAYMENT_SETTINGS
    {
        public int Payment_SettingId { get; set; }
        public string MarchantId { get; set; }
        public string Api_Key { get; set; }
        public string serviceTypeId { get; set; }
        public string Response_Url { get; set; }
        public string Description { get; set; }
        public int Fee_Schedule_Id { get; set; }
    
        public virtual FEE_SCHEDULE FEE_SCHEDULE { get; set; }
    }
}
