//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsPortal.Models.StudentsDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROOM_CAPACITY
    {
        public ROOM_CAPACITY()
        {
            this.ROOMS = new HashSet<ROOM>();
        }
    
        public int Room_Capacity_Id { get; set; }
        public int Room_Capacity_Number { get; set; }
    
        public virtual ICollection<ROOM> ROOMS { get; set; }
    }
}
