//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsPortal.Models.StudentsDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROOM
    {
        public ROOM()
        {
            this.HOSTEL_ALLOCATION_CRITERIA = new HashSet<HOSTEL_ALLOCATION_CRITERIA>();
            this.ROOM_CORNER = new HashSet<ROOM_CORNER>();
        }
    
        public long Room_Id { get; set; }
        public string Room_Name { get; set; }
        public int Room_Capacity_Id { get; set; }
        public Nullable<int> Series_Id { get; set; }
        public int Hostel_Id { get; set; }
        public Nullable<int> Series_Setting_Id { get; set; }
        public bool Activated { get; set; }
    
        public virtual HOSTEL HOSTEL { get; set; }
        public virtual ICollection<HOSTEL_ALLOCATION_CRITERIA> HOSTEL_ALLOCATION_CRITERIA { get; set; }
        public virtual ROOM_CAPACITY ROOM_CAPACITY { get; set; }
        public virtual ICollection<ROOM_CORNER> ROOM_CORNER { get; set; }
        public virtual SERIES SERIES { get; set; }
        public virtual SERIES_SETTING SERIES_SETTING { get; set; }
    }
}
