//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsPortal.Models.StudentsDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEMESTER
    {
        public SEMESTER()
        {
            this.COURSEs = new HashSet<COURSE>();
            this.COURSE_REGISTRATION = new HashSet<COURSE_REGISTRATION>();
            this.COURSE_UNIT_ALLOCATION = new HashSet<COURSE_UNIT_ALLOCATION>();
            this.FEE_DETAIL = new HashSet<FEE_DETAIL>();
            this.PAYMENTs = new HashSet<PAYMENT>();
            this.POSTGRADUATE_COURSE = new HashSet<POSTGRADUATE_COURSE>();
            this.POSTGRADUATE_COURSE_REGISTRATION = new HashSet<POSTGRADUATE_COURSE_REGISTRATION>();
            this.POSTGRADUATE_COURSE_UNIT_ALLOCATION = new HashSet<POSTGRADUATE_COURSE_UNIT_ALLOCATION>();
            this.SESSION_SEMESTER = new HashSet<SESSION_SEMESTER>();
            this.STAFF_RATING = new HashSet<STAFF_RATING>();
        }
    
        public int Semester_Id { get; set; }
        public string Semester_Name { get; set; }
    
        public virtual ICollection<COURSE> COURSEs { get; set; }
        public virtual ICollection<COURSE_REGISTRATION> COURSE_REGISTRATION { get; set; }
        public virtual ICollection<COURSE_UNIT_ALLOCATION> COURSE_UNIT_ALLOCATION { get; set; }
        public virtual ICollection<FEE_DETAIL> FEE_DETAIL { get; set; }
        public virtual ICollection<PAYMENT> PAYMENTs { get; set; }
        public virtual ICollection<POSTGRADUATE_COURSE> POSTGRADUATE_COURSE { get; set; }
        public virtual ICollection<POSTGRADUATE_COURSE_REGISTRATION> POSTGRADUATE_COURSE_REGISTRATION { get; set; }
        public virtual ICollection<POSTGRADUATE_COURSE_UNIT_ALLOCATION> POSTGRADUATE_COURSE_UNIT_ALLOCATION { get; set; }
        public virtual ICollection<SESSION_SEMESTER> SESSION_SEMESTER { get; set; }
        public virtual ICollection<STAFF_RATING> STAFF_RATING { get; set; }
    }
}
