//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsPortal.Models.StudentsDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERIES
    {
        public SERIES()
        {
            this.ROOMS = new HashSet<ROOM>();
            this.SERIES_SETTING = new HashSet<SERIES_SETTING>();
        }
    
        public int Series_Id { get; set; }
        public int Series_Name { get; set; }
        public Nullable<bool> Activated { get; set; }
    
        public virtual ICollection<ROOM> ROOMS { get; set; }
        public virtual ICollection<SERIES_SETTING> SERIES_SETTING { get; set; }
    }
}
