//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsPortal.Models.StudentsDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERIES_SETTING
    {
        public SERIES_SETTING()
        {
            this.HOSTEL_ALLOCATION_CRITERIA = new HashSet<HOSTEL_ALLOCATION_CRITERIA>();
            this.ROOMS = new HashSet<ROOM>();
        }
    
        public int Series_Setting_Id { get; set; }
        public int Hostel_Id { get; set; }
        public int Series_Id { get; set; }
        public int Number_of_Rooms { get; set; }
        public int Room_Capacity { get; set; }
        public bool Activated { get; set; }
    
        public virtual HOSTEL HOSTEL { get; set; }
        public virtual ICollection<HOSTEL_ALLOCATION_CRITERIA> HOSTEL_ALLOCATION_CRITERIA { get; set; }
        public virtual ICollection<ROOM> ROOMS { get; set; }
        public virtual SERIES SERIES { get; set; }
    }
}
