//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsPortal.Models.StudentsDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class SESSION
    {
        public SESSION()
        {
            this.ADMISSIONS = new HashSet<ADMISSION>();
            this.COURSEs = new HashSet<COURSE>();
            this.COURSE_REGISTRATION = new HashSet<COURSE_REGISTRATION>();
            this.COURSE_UNIT_ALLOCATION = new HashSet<COURSE_UNIT_ALLOCATION>();
            this.ETRANZACT_TERMINAL = new HashSet<ETRANZACT_TERMINAL>();
            this.FEE_DETAIL = new HashSet<FEE_DETAIL>();
            this.JUPEB_ADMISSIONS = new HashSet<JUPEB_ADMISSIONS>();
            this.JUPEB_PROSPECTIVE_APPLIED_COURSE = new HashSet<JUPEB_PROSPECTIVE_APPLIED_COURSE>();
            this.PAYMENTs = new HashSet<PAYMENT>();
            this.POSTGRADUATE_ADMISSIONS = new HashSet<POSTGRADUATE_ADMISSIONS>();
            this.POSTGRADUATE_APPLIED_COURSE = new HashSet<POSTGRADUATE_APPLIED_COURSE>();
            this.POSTGRADUATE_COURSE = new HashSet<POSTGRADUATE_COURSE>();
            this.POSTGRADUATE_COURSE_UNIT_ALLOCATION = new HashSet<POSTGRADUATE_COURSE_UNIT_ALLOCATION>();
            this.POSTGRADUATE_STUDENT_LEVEL = new HashSet<POSTGRADUATE_STUDENT_LEVEL>();
            this.PROSPECTIVE_APPLIED_COURSE = new HashSet<PROSPECTIVE_APPLIED_COURSE>();
            this.PROSPECTIVE_SECOND_APPLIED_COURSE = new HashSet<PROSPECTIVE_SECOND_APPLIED_COURSE>();
            this.SESSION_SEMESTER = new HashSet<SESSION_SEMESTER>();
            this.STAFF_RATING = new HashSet<STAFF_RATING>();
            this.STUDENT_LEVEL = new HashSet<STUDENT_LEVEL>();
        }
    
        public int Session_Id { get; set; }
        public string Session_Name { get; set; }
        public Nullable<bool> Activated { get; set; }
    
        public virtual ICollection<ADMISSION> ADMISSIONS { get; set; }
        public virtual ICollection<COURSE> COURSEs { get; set; }
        public virtual ICollection<COURSE_REGISTRATION> COURSE_REGISTRATION { get; set; }
        public virtual ICollection<COURSE_UNIT_ALLOCATION> COURSE_UNIT_ALLOCATION { get; set; }
        public virtual ICollection<ETRANZACT_TERMINAL> ETRANZACT_TERMINAL { get; set; }
        public virtual ICollection<FEE_DETAIL> FEE_DETAIL { get; set; }
        public virtual ICollection<JUPEB_ADMISSIONS> JUPEB_ADMISSIONS { get; set; }
        public virtual ICollection<JUPEB_PROSPECTIVE_APPLIED_COURSE> JUPEB_PROSPECTIVE_APPLIED_COURSE { get; set; }
        public virtual ICollection<PAYMENT> PAYMENTs { get; set; }
        public virtual ICollection<POSTGRADUATE_ADMISSIONS> POSTGRADUATE_ADMISSIONS { get; set; }
        public virtual ICollection<POSTGRADUATE_APPLIED_COURSE> POSTGRADUATE_APPLIED_COURSE { get; set; }
        public virtual ICollection<POSTGRADUATE_COURSE> POSTGRADUATE_COURSE { get; set; }
        public virtual ICollection<POSTGRADUATE_COURSE_UNIT_ALLOCATION> POSTGRADUATE_COURSE_UNIT_ALLOCATION { get; set; }
        public virtual ICollection<POSTGRADUATE_STUDENT_LEVEL> POSTGRADUATE_STUDENT_LEVEL { get; set; }
        public virtual ICollection<PROSPECTIVE_APPLIED_COURSE> PROSPECTIVE_APPLIED_COURSE { get; set; }
        public virtual ICollection<PROSPECTIVE_SECOND_APPLIED_COURSE> PROSPECTIVE_SECOND_APPLIED_COURSE { get; set; }
        public virtual ICollection<SESSION_SEMESTER> SESSION_SEMESTER { get; set; }
        public virtual ICollection<STAFF_RATING> STAFF_RATING { get; set; }
        public virtual ICollection<STUDENT_LEVEL> STUDENT_LEVEL { get; set; }
    }
}
