//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsPortal.Models.StudentsDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class SESSION_SEMESTER
    {
        public SESSION_SEMESTER()
        {
            this.COURSE_TIME_TABLE_SCHEDULE = new HashSet<COURSE_TIME_TABLE_SCHEDULE>();
        }
    
        public int Session_Semester_Id { get; set; }
        public int Session_Id { get; set; }
        public int Semester_Id { get; set; }
        public System.DateTime Semester_Start_Date { get; set; }
        public System.DateTime Semester_End_Date { get; set; }
        public bool Activated { get; set; }
    
        public virtual ICollection<COURSE_TIME_TABLE_SCHEDULE> COURSE_TIME_TABLE_SCHEDULE { get; set; }
        public virtual SEMESTER SEMESTER { get; set; }
        public virtual SESSION SESSION { get; set; }
    }
}
