//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsPortal.Models.StudentsDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAFF
    {
        public STAFF()
        {
            this.STAFF_PUBLICATIONS = new HashSet<STAFF_PUBLICATIONS>();
            this.STAFF_QUALIFICATIONS = new HashSet<STAFF_QUALIFICATIONS>();
            this.STAFF_WORKING_EXPERIENCE = new HashSet<STAFF_WORKING_EXPERIENCE>();
        }
    
        public long Staff_Id { get; set; }
        public Nullable<int> Department_Id { get; set; }
        public bool Activated { get; set; }
        public System.DateTime Date_Entered { get; set; }
        public long Entered_By { get; set; }
        public Nullable<System.DateTime> Appointment_Date { get; set; }
        public string Appointment_Nature { get; set; }
        public Nullable<System.DateTime> Assumption_Date { get; set; }
        public string Rank { get; set; }
        public Nullable<int> Faculty_Id { get; set; }
        public Nullable<System.DateTime> Dismissal_Date { get; set; }
        public Nullable<System.DateTime> Retirement_Date { get; set; }
        public Nullable<System.DateTime> Resign_Date { get; set; }
        public int Staff_Type_Id { get; set; }
    
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        public virtual FACULTY FACULTY { get; set; }
        public virtual PERSON PERSON { get; set; }
        public virtual ICollection<STAFF_PUBLICATIONS> STAFF_PUBLICATIONS { get; set; }
        public virtual ICollection<STAFF_QUALIFICATIONS> STAFF_QUALIFICATIONS { get; set; }
        public virtual STAFF_TYPE STAFF_TYPE { get; set; }
        public virtual USER USER { get; set; }
        public virtual ICollection<STAFF_WORKING_EXPERIENCE> STAFF_WORKING_EXPERIENCE { get; set; }
    }
}
