//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsPortal.Models.StudentsDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAFF_PUBLICATIONS
    {
        public int Publication_Id { get; set; }
        public int Publication_Type_Id { get; set; }
        public string Publication_Title { get; set; }
        public Nullable<int> Publication_Serial_Number { get; set; }
        public string Publication_Url { get; set; }
        public long Staff_Id { get; set; }
        public Nullable<System.DateTime> Publication_Date { get; set; }
    
        public virtual PUBLICATION_TYPE PUBLICATION_TYPE { get; set; }
        public virtual STAFF STAFF { get; set; }
    }
}
