//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsPortal.Models.StudentsDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAFF_IMAGES
    {
        public int Image_Id { get; set; }
        public string Image_Name { get; set; }
        public string Image_Url { get; set; }
        public long Staff_Id { get; set; }
    }
}
