//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsPortal.Models.StudentsDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAFF_WORKING_EXPERIENCE
    {
        public int Experience_Id { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string OrganisationName { get; set; }
        public string Position { get; set; }
        public string Description { get; set; }
        public long Staff_Id { get; set; }
    
        public virtual STAFF STAFF { get; set; }
    }
}
