//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsPortal.Models.StudentsDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class STATE
    {
        public STATE()
        {
            this.LOCAL_GOVERNMENT = new HashSet<LOCAL_GOVERNMENT>();
            this.People = new HashSet<PERSON>();
            this.TRANSCRIPT_REQUEST = new HashSet<TRANSCRIPT_REQUEST>();
        }
    
        public string State_Id { get; set; }
        public string State_Name { get; set; }
        public int Nationality_Id { get; set; }
    
        public virtual COUNTRY COUNTRY { get; set; }
        public virtual ICollection<LOCAL_GOVERNMENT> LOCAL_GOVERNMENT { get; set; }
        public virtual ICollection<PERSON> People { get; set; }
        public virtual ICollection<TRANSCRIPT_REQUEST> TRANSCRIPT_REQUEST { get; set; }
    }
}
