//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsPortal.Models.StudentsDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_GRADE
    {
        public STUDENT_GRADE()
        {
            this.COURSE_REGISTRATION = new HashSet<COURSE_REGISTRATION>();
            this.POSTGRADUATE_COURSE_REGISTRATION = new HashSet<POSTGRADUATE_COURSE_REGISTRATION>();
            this.STUDENT_RESULT = new HashSet<STUDENT_RESULT>();
        }
    
        public int Student_Grade_Id { get; set; }
        public string Student_Grade_Name { get; set; }
        public double Score_From { get; set; }
        public double Score_To { get; set; }
        public bool Activated { get; set; }
        public int Grade_Point { get; set; }
    
        public virtual ICollection<COURSE_REGISTRATION> COURSE_REGISTRATION { get; set; }
        public virtual ICollection<POSTGRADUATE_COURSE_REGISTRATION> POSTGRADUATE_COURSE_REGISTRATION { get; set; }
        public virtual ICollection<STUDENT_RESULT> STUDENT_RESULT { get; set; }
    }
}
