//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsPortal.Models.StudentsDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_HOSTEL
    {
        public int Student_Hostel_Id { get; set; }
        public long Room_Id { get; set; }
        public int Hostel_Id { get; set; }
        public byte Hostel_Gender_Id { get; set; }
        public int Series_Id { get; set; }
        public int Session_Id { get; set; }
        public long Student_Id { get; set; }
        public long Student_Level_Id { get; set; }
        public long Room_Corner_Id { get; set; }
        public int Series_Setting_Id { get; set; }
    
        public virtual STUDENT STUDENT { get; set; }
    }
}
