//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsPortal.Models.StudentsDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSCRIPT_REQUEST
    {
        public long Transcript_Request_Id { get; set; }
        public long Student_id { get; set; }
        public Nullable<long> Payment_Id { get; set; }
        public System.DateTime Date_Requested { get; set; }
        public string Destination_Address { get; set; }
        public string Destination_State_Id { get; set; }
        public string Destination_Country_Id { get; set; }
        public Nullable<int> Transcript_clearance_Status_Id { get; set; }
        public int Transcript_Status_Id { get; set; }
    
        public virtual PAYMENT PAYMENT { get; set; }
        public virtual STATE STATE { get; set; }
        public virtual STUDENT STUDENT { get; set; }
        public virtual TRANSCRIPT_CLEARANCE_STATUS TRANSCRIPT_CLEARANCE_STATUS { get; set; }
        public virtual TRANSCRIPT_STATUS TRANSCRIPT_STATUS { get; set; }
    }
}
