//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsPortal.Models.StudentsDetails
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class USER
    {
        public USER()
        {
            this.ADMISSIONS = new HashSet<ADMISSION>();
            this.APPOINTMENTs = new HashSet<APPOINTMENT>();
            this.APPOINTMENTs1 = new HashSet<APPOINTMENT>();
            this.APPOINTMENT_ALLOCATION = new HashSet<APPOINTMENT_ALLOCATION>();
            this.APPOINTMENT_ALLOCATION1 = new HashSet<APPOINTMENT_ALLOCATION>();
            this.AUDIT_TRAIL = new HashSet<AUDIT_TRAIL>();
            this.COURSE_REGISTRATION = new HashSet<COURSE_REGISTRATION>();
            this.COURSE_TIME_TABLE_SCHEDULE = new HashSet<COURSE_TIME_TABLE_SCHEDULE>();
            this.EVENTS = new HashSet<EVENT>();
            this.JUPEB_ADMISSIONS = new HashSet<JUPEB_ADMISSIONS>();
            this.NEWS = new HashSet<NEWS>();
            this.POSTGRADUATE_ADMISSIONS = new HashSet<POSTGRADUATE_ADMISSIONS>();
            this.QUIZ_TIME_TABLE_SCHEDULE = new HashSet<QUIZ_TIME_TABLE_SCHEDULE>();
            this.STAFFs = new HashSet<STAFF>();
            this.STAFF_COURSE_ALLOCATION = new HashSet<STAFF_COURSE_ALLOCATION>();
            this.STAFF_RATING = new HashSet<STAFF_RATING>();
            this.STUDENT_RESULT = new HashSet<STUDENT_RESULT>();
            this.USER_RIGHT = new HashSet<USER_RIGHT>();
        }
    
        public long User_Id { get; set; }

        [Display(Name="User Name")]
        public string User_Name { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public int Role_Id { get; set; }
        public long Person_Id { get; set; }
    
        public virtual ICollection<ADMISSION> ADMISSIONS { get; set; }
        public virtual ICollection<APPOINTMENT> APPOINTMENTs { get; set; }
        public virtual ICollection<APPOINTMENT> APPOINTMENTs1 { get; set; }
        public virtual ICollection<APPOINTMENT_ALLOCATION> APPOINTMENT_ALLOCATION { get; set; }
        public virtual ICollection<APPOINTMENT_ALLOCATION> APPOINTMENT_ALLOCATION1 { get; set; }
        public virtual ICollection<AUDIT_TRAIL> AUDIT_TRAIL { get; set; }
        public virtual ICollection<COURSE_REGISTRATION> COURSE_REGISTRATION { get; set; }
        public virtual ICollection<COURSE_TIME_TABLE_SCHEDULE> COURSE_TIME_TABLE_SCHEDULE { get; set; }
        public virtual ICollection<EVENT> EVENTS { get; set; }
        public virtual ICollection<JUPEB_ADMISSIONS> JUPEB_ADMISSIONS { get; set; }
        public virtual ICollection<NEWS> NEWS { get; set; }
        public virtual PERSON PERSON { get; set; }
        public virtual ICollection<POSTGRADUATE_ADMISSIONS> POSTGRADUATE_ADMISSIONS { get; set; }
        public virtual ICollection<QUIZ_TIME_TABLE_SCHEDULE> QUIZ_TIME_TABLE_SCHEDULE { get; set; }
        public virtual ROLE ROLE { get; set; }
        public virtual ICollection<STAFF> STAFFs { get; set; }
        public virtual ICollection<STAFF_COURSE_ALLOCATION> STAFF_COURSE_ALLOCATION { get; set; }
        public virtual ICollection<STAFF_RATING> STAFF_RATING { get; set; }
        public virtual ICollection<STUDENT_RESULT> STUDENT_RESULT { get; set; }
        public virtual ICollection<USER_RIGHT> USER_RIGHT { get; set; }
    }
}
