//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsPortal.Models.StudentsDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISITATION_REGISTATION
    {
        public long Visitation_Id { get; set; }
        public string Visitor_Name { get; set; }
        public string Phone_Number { get; set; }
        public string Host { get; set; }
        public System.DateTime Time_In { get; set; }
        public Nullable<System.DateTime> Time_Out { get; set; }
    }
}
