//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsPortal.Models.StudentsDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_JUPEB_ADMISSION
    {
        public long Person_Id { get; set; }
        public string Faculty_Name { get; set; }
        public int Jupeb_Subject_Combination_Id { get; set; }
        public string Appication_Number { get; set; }
        public Nullable<bool> Admitted { get; set; }
        public long Jupeb_Admission_Id { get; set; }
        public string Jupeb_Subject_Name { get; set; }
        public string Session_Name { get; set; }
        public int Session_Id { get; set; }
        public string Programme_Name { get; set; }
        public string fullname { get; set; }
        public string Contact_Address { get; set; }
        public string Email_Address { get; set; }
        public string Mobile_Phone { get; set; }
        public Nullable<System.DateTime> Date_Of_Birth { get; set; }
        public string Home_Address { get; set; }
        public string Home_Town { get; set; }
    }
}
