//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsPortal.Models.StudentsDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_JUPEB_ACADEMIC_REPORT
    {
        public string Olevel_Exam_Name { get; set; }
        public Nullable<int> Olevel_Exam_Attempt_Id { get; set; }
        public long OLevel_Result_Id { get; set; }
        public string OLevel_Subject_Grade_Name { get; set; }
        public string OLevel_Subject_Name { get; set; }
        public int OLevel_Subject_Id { get; set; }
        public int Expr1 { get; set; }
        public string OLevel_Exam_Attempt_Name { get; set; }
        public string Session_Name { get; set; }
        public int Session_Id { get; set; }
        public string Appication_Number { get; set; }
        public int Jupeb_Subject_Combination_Id { get; set; }
        public string name { get; set; }
        public string Olevel_Exam_Number { get; set; }
        public Nullable<int> Olevel_Exam_Year { get; set; }
        public string fullname { get; set; }
    }
}
