//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsPortal.Models.StudentsDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_POSTGRADUATE_PROSPCTIVE_PAYMENT
    {
        public int Fee_Schedule_Id { get; set; }
        public string Fee_Schedule_Name { get; set; }
        public long Payment_Id { get; set; }
        public string Appication_Number { get; set; }
        public Nullable<bool> Admitted { get; set; }
        public int Session_Id { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Other_Name { get; set; }
        public long Person_Id { get; set; }
        public string Confirmation_No { get; set; }
        public string Invoice_Number { get; set; }
        public Nullable<decimal> Transaction_Amount { get; set; }
        public string Session_Name { get; set; }
        public string Course_Name { get; set; }
        public string Department_Name { get; set; }
        public int PostGraduate_Department_Id { get; set; }
        public string Faculty_Name { get; set; }
        public Nullable<int> Status_Id { get; set; }
    }
}
