//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsPortal.Models.StudentsDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_STUDENT_DEPARTMENT_HOSTEL_REPORT
    {
        public long Person_Id { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Other_Name { get; set; }
        public string Matric_Number { get; set; }
        public string Hostel_Name { get; set; }
        public string Department_Name { get; set; }
        public int Department_Id { get; set; }
        public string Room_Name { get; set; }
        public long Room_Id { get; set; }
        public long Room_Corner_Id { get; set; }
        public string Room_Corner_Name { get; set; }
        public string Session_Name { get; set; }
        public int Session_Id { get; set; }
        public string Gender_Name { get; set; }
        public string Level_Name { get; set; }
        public int Level_Id { get; set; }
        public int Expr1 { get; set; }
        public int Hostel_Id { get; set; }
    }
}
