//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsPortal.Models.StudentsDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_STUDENT_PAYMENT
    {
        public Nullable<decimal> Transaction_Amount { get; set; }
        public Nullable<System.DateTime> Transaction_Date { get; set; }
        public string Confirmation_No { get; set; }
        public int Fee_Schedule_Id { get; set; }
        public string Invoice_Number { get; set; }
        public Nullable<int> Session_Id { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Other_Name { get; set; }
        public int Level_Id { get; set; }
        public int Programme_Id { get; set; }
        public int Department_Id { get; set; }
        public string Matric_Number { get; set; }
        public string Fee_Schedule_Name { get; set; }
        public string Department_Name { get; set; }
        public string Programme_Name { get; set; }
        public string Level_Name { get; set; }
        public string Session_Name { get; set; }
        public string Faculty_Name { get; set; }
        public int Faculty_Id { get; set; }
    }
}
